---
- name: Update apt repositories cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: '{{ package_cache_expiry }}'
  when: is_linux

- name: Update brew repositories cache
  community.general.homebrew:
    update_homebrew: true
  when: is_macos
