---
- name: Update apt packages
  become: true
  ansible.builtin.apt:
    upgrade: full
  when: is_linux

- name: Update brew packages
  community.general.homebrew:
    upgrade_all: true
  when: is_macos
