---
- name: Install zsh and plugins
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - zsh
      - zsh-syntax-highlighting

- name: Set as default shell
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    shell: /usr/bin/zsh

- name: Link my zsh config file
  ansible.builtin.file:
    src: '{{ dotfiles_dir }}/.zshrc'
    dest: ~/.zshrc
    force: true
    mode: '0644'
    state: link

- name: Create empty profile file
  ansible.builtin.copy:
    dest: ~/.profile
    content: ''
    mode: '0644'
    force: false
