---
- name: Remove useless packages from the cache
  become: true
  ansible.builtin.apt:
    autoclean: true

- name: Remove dependencies that are no longer required
  become: true
  ansible.builtin.apt:
    autoremove: true
