---
- name: Update cache
  ansible.builtin.include_tasks: update.yml

- name: Upgrade packages
  ansible.builtin.include_tasks: upgrade.yml

- name: Clean cache
  ansible.builtin.include_tasks: clean.yml

- name: Check if reboot is needed
  ansible.builtin.include_tasks: reboot.yml
