---
- name: PC Playbook
  hosts: all
  become: true

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Load configuration
      ansible.builtin.include_vars: '{{ item }}'
      with_fileglob:
        - '{{ playbook_dir }}/config.yml'

  roles:
    - update_os
    - gantsign.oh-my-zsh
    - geerlingguy.pip
    - geerlingguy.ansible
    - git
    - shell
