---
- name: PC Playbook
  hosts: all

  vars:
    should_be_root: "{{ false if ansible_os_family == 'Darwin' else true }}"

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Display OS and if should be should be root
      ansible.builtin.debug:
        msg:
          - 'OS is: {{ ansible_os_family }}'
          - 'Should root be used? {{ should_be_root }}'

    - name: Load configuration
      ansible.builtin.include_vars: '{{ item }}'
      with_fileglob:
        - '{{ playbook_dir }}/config.yml'

  roles:
    - package_manager
    - system
    - git
    - github
    - shell
    - python
    - node
