---
- name: Install python
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - python3

- name: Install pip in Linux
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - python3-pip
  when: ansible_system == 'Linux'

- name: Install pip recommended packages
  ansible.builtin.pip:
    name: '{{ item }}'
    extra_args: --upgrade
  loop: '{{ pip_recommended_packages }}'
