---
- name: Setup each dock item
  ansible.builtin.set_fact:
    # yamllint disable rule:line-length
    macos_dock_item_configs: "{{ macos_dock_items | map('regex_replace', '(.*)', '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/\\1.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>') | list }}"
    # yamllint enable rule:line-length

- name: Add all items to dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    type: array
    value: '{{ macos_dock_item_configs }}'
  changed_when: false

- name: Setup Dock options
  community.general.osx_defaults:
    domain: com.apple.dock
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop: '{{ macos_dock_options }}'

- name: LaunchPad reset
  community.general.osx_defaults:
    domain: com.apple.dock
    key: ResetLaunchPad
    type: bool
    value: true
  changed_when: false

- name: Restart Dock
  ansible.builtin.command: killall Dock
  register: macos_dock_kill
  changed_when: false
