---
- name: Setup Finder options
  community.general.osx_defaults:
    domain: com.apple.finder
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop: '{{ macos_finder_options }}'

- name: Show the user home Library folder
  ansible.builtin.command: chflags nohidden ~/Library
  register: macos_finder_kill
  changed_when: false

- name: Calculate all sizes in folders
  # yamllint disable rule:line-length
  ansible.builtin.shell: |
    /usr/libexec/PlistBuddy "$HOME/Library/Preferences/com.apple.finder.plist" -c 'Delete "StandardViewSettings:ExtendedListViewSettings:calculateAllSizes" bool'
    /usr/libexec/PlistBuddy "$HOME/Library/Preferences/com.apple.finder.plist" -c 'Add "StandardViewSettings:ExtendedListViewSettings:calculateAllSizes" bool true'

    /usr/libexec/PlistBuddy "$HOME/Library/Preferences/com.apple.finder.plist" -c 'Delete "StandardViewSettings:ListViewSettings:calculateAllSizes" bool'
    /usr/libexec/PlistBuddy "$HOME/Library/Preferences/com.apple.finder.plist" -c 'Add "StandardViewSettings:ListViewSettings:calculateAllSizes" bool true'
  # yamllint enable rule:line-length
  register: macos_finder_file_sizes
  changed_when: false

- name: Restart Finder
  ansible.builtin.command: killall Finder
  register: macos_finder_kill
  changed_when: false
