---
- name: Close Preferences before changes
  ansible.builtin.command: osascript -e 'tell application "System Preferences" to quit'
  register: macos_close_preferences
  changed_when: false

- name: Setup dock
  ansible.builtin.include_tasks: dock.yml

- name: Setup finder
  ansible.builtin.include_tasks: finder.yml

- name: Setup software updates
  ansible.builtin.include_tasks: update.yml

- name: Setup options
  ansible.builtin.include_tasks: options.yml
