---
- name: Setup Software Update options
  become: true
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.SoftwareUpdate
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop: '{{ macos_software_update_options }}'

- name: Setup App Store options
  become: true
  community.general.osx_defaults:
    domain: /Library/Preferences/com.apple.commerce
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
  loop: '{{ macos_finder_options }}'
