---
- name: Set hostname
  ansible.builtin.include_tasks: hostname.yml

- name: Configure sudo
  ansible.builtin.include_tasks: sudo.yml

- name: Install recommended packages
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name: '{{ recommended_packages }}'
