---
- name: Install python and pip
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - python3
      - python3-pip

- name: Install ansible
  ansible.builtin.pip:
    name: '{{ item }}'
  loop:
    - ansible
    - ansible-lint
