---
- name: Install python
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - python3

- name: Install pip
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - python3-pip
  when: use_apt

- name: Install ansible
  ansible.builtin.pip:
    name: '{{ item }}'
  loop:
    - ansible
    - ansible-lint
    - jmespath

- name: Get outdated pip packages information
  ansible.builtin.command:
    cmd: pip3 --disable-pip-version-check list --outdated --format=json
  register: pip_outdated_info
  changed_when: false

- name: List outdated pip packages
  ansible.builtin.set_fact:
    pip_outdated_packages: '{{ pip_outdated_info.stdout | from_json | community.general.json_query("[*].name") }}'
