---
- name: Install python and pip
  become: true
  ansible.builtin.apt:
    pkg:
      - python3
      - python3-pip

- name: Install ansible
  ansible.builtin.pip:
    name: '{{ item }}'
  loop:
    - ansible
    - ansible-lint
