---
- name: Install python
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - python3

- name: Install pip
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - python3-pip
  when: should_be_root

- name: Install ansible
  ansible.builtin.pip:
    name: '{{ item }}'
  loop:
    - ansible
    - ansible-lint
