---
- name: Install dev languages
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - golang-go
      - default-jdk
      - ruby-full
      - rustc
  when: is_linux

- name: Install dev languages
  ansible.builtin.package:
    name:
      - go
      - openjdk
      - ruby
      - rust
  when: is_macos

- name: Install dev utils
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - httpie
      - qemu

- name: Install dev utils
  community.general.homebrew_cask:
    name: font-jetbrains-mono
  when: is_macos

- name: Install Visual Studio Code
  community.general.homebrew_cask:
    name: visual-studio-code
  when: is_macos

- name: Install Docker
  community.general.homebrew_cask:
    name: docker
  when: is_macos

- name: Install infra apps
  ansible.builtin.package:
    name:
      - dive
      - hadolint
      - helm
      - kubernetes-cli
      - minikube
  when: is_macos

- name: Add Hashicorp apt key
  become: '{{ should_be_root }}'
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp Repository
  become: '{{ should_be_root }}'
  ansible.builtin.apt_repository:
    repo: deb https://apt.releases.hashicorp.com {{ ansible_lsb.codename }} main
    filename: hashicorp
    state: present
  when: is_linux

- name: Install Terraform
  become: '{{ should_be_root }}'
  ansible.builtin.package:
    name:
      - terraform

- name: Install browsers
  community.general.homebrew_cask:
    name: '{{ item }}'
  loop:
    - firefox
    - microsoft-edge
  when: is_macos

- name: Chat apps
  community.general.homebrew_cask:
    name: slack
  when: is_macos
