---
- name: Install browsers
  community.general.homebrew_cask:
    name: '{{ item }}'
  loop:
    - google-chrome

- name: Install QuickLook plugins
  community.general.homebrew_cask:
    name: '{{ item }}'
  loop:
    - qlcolorcode
    - qlimagesize
    - qlmarkdown
    - quicklook-csv
    - quicklook-json
    - webpquicklook

- name: Install apps
  community.general.homebrew_cask:
    name: '{{ item }}'
  loop:
    - coconutbattery
    - google-drive
    - logi-options-plus
    - smcfancontrol
    - spectacle
    - spotify
    - stats
    - the-unarchiver
    - vlc
