---
- name: Install browsers
  community.general.homebrew_cask:
    name: '{{ item }}'
  loop:
    - google-chrome

- name: Set Chrome as default browser
  ansible.builtin.command:
    cmd: open -a "Google Chrome" --args --make-default-browser
  register: chrome_default
  changed_when: false

- name: Install QuickLook plugins
  community.general.homebrew_cask:
    name: '{{ item }}'
  loop:
    - qlcolorcode
    - qlimagesize
    - qlmarkdown
    - quicklook-csv
    - quicklook-json
    - webpquicklook

- name: Add support for quicklook plugins in macOS >= 10.15
  ansible.builtin.command: xattr -d -r com.apple.quarantine ~/Library/QuickLook
  register: quicklook_plugins_support
  changed_when: false

- name: Install apps
  community.general.homebrew_cask:
    name: '{{ item }}'
  loop:
    - coconutbattery
    - google-drive
    - logi-options-plus
    - smcfancontrol
    - spectacle
    - spotify
    - stats
    - the-unarchiver
    - vlc

- name: Spectacle status
  community.general.osx_defaults:
    domain: com.divisiblebyzero.Spectacle
    key: StatusItemEnabled
    type: bool
    value: false

- name: Add Spectacle to login items
  ansible.builtin.command: osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Spectacle.app", hidden:true, name:"Spectacle"}'
  register: spectacle_login
  changed_when: false
