---
- name: Install essential apps
  ansible.builtin.include_tasks: essentials.yml
  when: is_macos

- name: Install dev languages and apps
  ansible.builtin.include_tasks: dev.yml

- name: Install social apps
  ansible.builtin.include_tasks: social.yml
  when: is_macos

- name: Install games apps
  ansible.builtin.include_tasks: games.yml
  when: is_macos
