---
- name: Download nvm install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/master/install.sh
    dest: /tmp/nvm_install.sh
    mode: '0755'

- name: Run nvm install script
  ansible.builtin.command: zsh /tmp/nvm_install.sh
  args:
    creates: '{{ ansible_env.HOME }}/.nvm/nvm.sh'
  register: nvm_install
  changed_when: false

- name: Configure nvm
  ansible.builtin.shell: |
    . {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm install --lts --no-progress
    nvm alias default system
  register: nvm_configure
  changed_when: false
